# Generated by Django 4.2.2 on 2023-06-06 16:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mov', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MergedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='Merged_uploaded')),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploadedmovie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.uploadedmovie')),
            ],
        ),
    ]
